# netlify.toml

# Example existing build and functions configuration
[build]
  command = "next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
