name: Fetch Games Updates (daily)

permissions:
  contents: read

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Fetch RAWG popular releases (last 30 days)
        env:
          RAWG_KEY: ${{ secrets.RAWG_KEY }}
        run: |
          mkdir -p data
          start=$(date -d "30 days ago" +%F)
          end=$(date +%F)
          curl -s \
            "https://api.rawg.io/api/games?key=$RAWG_KEY&dates=$start,$end&ordering=-rating&page_size=10" \
            > raw_games.json

      - name: Trim RAWG payload
        run: |
          node <<'NODE'
          const fs = require('fs');
          const src = JSON.parse(fs.readFileSync('raw_games.json', 'utf8'));

          if (!Array.isArray(src.results)) {
            console.error('Unexpected RAWG payload', JSON.stringify(src).slice(0,200));
            process.exit(0);
          }

          // Keep only id, name, background_image, released
          const out = src.results.map(g => ({
            id: g.id,
            name: g.name,
            thumbnail: g.background_image,
            released: g.released
          }));

          fs.writeFileSync('data/games.json', JSON.stringify(out, null, 2));
          NODE


      - name: Update MongoDB with new data
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB: ${{ secrets.MONGODB_DB }}
        run: npm run migrate
