name: Fetch Tech Headlines

permissions:
  contents: read

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-tech:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Fetch top Hacker News stories
        run: |
          TOP_IDS=$(curl -s https://hacker-news.firebaseio.com/v0/topstories.json | jq '.[0:10]')
          STORIES=$(echo "$TOP_IDS" | jq -r '.[]' | while read ID; do
            curl -s "https://hacker-news.firebaseio.com/v0/item/${ID}.json" \
              | jq '{ id: .id, title: .title, url: .url }'
          done | jq -s '.')
          echo "$STORIES" > tech.json


      - name: Push to MongoDB (tech)
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB: ${{ secrets.MONGODB_DB }}
        run: |
          node --loader ts-node/esm --experimental-specifier-resolution=node scripts/push-to-mongo.ts \
            --file tech.json --collection tech
