name: Fetch NASA Data

permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-nasa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Fetch APOD
        env:
          NASA_KEY: ${{ secrets.NASA_KEY }}
        run: |
          mkdir -p data
          curl --silent "https://api.nasa.gov/planetary/apod?api_key=$NASA_KEY&thumbs=true" > src/data/space.json

      - name: Fetch NASA Breaking News
        run: |
          curl -s https://www.nasa.gov/rss/dyn/breaking_news.rss > news.xml
          python3 - <<'PY'
          import json, xml.etree.ElementTree as ET
          root = ET.parse('news.xml').getroot()
          items = []
          for item in root.findall('./channel/item')[:10]:
              items.append({
                  'title': item.findtext('title'),
                  'pubDate': item.findtext('pubDate'),
                  'link': item.findtext('link'),
                  'summary': item.findtext('description')
              })
          with open('src/data/nasaNews.json', 'w') as f:
              json.dump(items, f, indent=2)
          PY

      - name: Fetch Mars Rover Photo
        env:
          NASA_KEY: ${{ secrets.NASA_KEY }}
        run: |
          TODAY=$(date -u +%Y-%m-%d)
          curl -s "https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?earth_date=$TODAY&api_key=$NASA_KEY" \
            | jq '{photos: .photos[0:1] | map({id: .id, img_src: .img_src, camera: .camera.full_name, rover: .rover.name})}' > src/data/marsPhoto.json

      - name: Fetch EPIC Earth image
        env:
          NASA_KEY: ${{ secrets.NASA_KEY }}
        run: |
          curl -s "https://api.nasa.gov/EPIC/api/natural?api_key=$NASA_KEY" \
            | jq '.[0] | {date: .date, image: .image, caption: .caption}' > src/data/epic.json

      - name: Fetch Mars Weather
        env:
          NASA_KEY: ${{ secrets.NASA_KEY }}
        run: |
          curl -s "https://api.nasa.gov/insight_weather/?api_key=$NASA_KEY&feedtype=json&ver=1.0" > weather_raw.json
          jq '{sol_keys: .sol_keys, latest: (.sol_keys[-1] as $s | .[$s] | {sol: $s, AT: .AT.av, HWS: .HWS.av, PRE: .PRE.av})}' weather_raw.json > src/data/marsWeather.json

      - name: Commit & push updated NASA data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/space.json src/data/nasaNews.json src/data/marsPhoto.json src/data/epic.json src/data/marsWeather.json
          git diff --cached --quiet && exit 0
          git commit -m "chore: update NASA data"
          git push
